# Generated by Django 5.1.6 on 2025-02-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
