# Generated by Django 5.1.6 on 2025-02-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_todo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline_value',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='todo',
            name='order',
            field=models.FloatField(default=0),
        ),
    ]
