# Generated by Django 5.1.6 on 2025-02-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_remove_todo_deadline_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='value',
            field=models.FloatField(default=5),
        ),
    ]
